### ISSUE TITLE
pipanel app breaks ALL themes

### ISSUE THREAD

**Issue by paulwratt** [raspberrypi/pipanel#6]
I like someone took time to customize Pi, but this app sux more every time it is released. So instead of only complaining about it I am willing to test the bagesus out of it until it stop getting in the way of "above average Pi user experience".
-------------------------------------

As soon as you click it (it opens) it set "Window Theme" to "Pix" and "Widget Theme" to "Pix" and sets new "Global Hilite Color".

It breaks ALL themes by overriding "File Hilite Color", "Menu(Task) Bar Hilite Color" with the same one used for "Menu Hilite Color" (the only one you can actually set in app).

1) I can see that pipanel "set defaults" runs EVERY time app is started, instead of ONLY when button pushed
2) set Hilite Color is global, an if u want it, it should have tickbox "set global hilite", otherwise it should "use theme hilite"
3) you should at least be able to set "Menu (Task) Bar Hilite", "Menu Hilite" and "File Hilite" seperately.

Someone assist me with this or I start de-code-ing pipanel and NO-ONE will like it.

pipanel seems small enuf I can run repo clone (if that is easiest dev option)

I see now "greeter" or "pi-greeter" is dependant on pipanel, why and what does it do (besides 1st time startup - which is actually 1st time run, ie runs every time it is updated)

I have (clean) thread on raspberry pi forum is greater discussion is required:
[https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=165555&p=1067293](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=165555&p=1067293)

Cheer, and may the testing begin

Paul

**Comment by paulwratt** [comment]
K, I have cloned pipanel on github, and cloned that to local, set up Oauth token and ssh keys, and I am pretty sure I can setup remote fetch to original repo when someone starts doing something.

I am 1st going to disable "set defaults" on pipanel startup, as it kills my theme, desktop, and background. Extremely painful when testing..

**Comment by spl237** [comment]
This is how pipanel is intended to work - it deliberately forces use of the PiX theme. If you don't want to use the PiX theme, don't run pipanel.
